Section "ServerLayout"
    Identifier "Default Layout"
    Screen 0 "Screen0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Card0"
EndSection

Section "Device"
    Identifier "Card0"
    Driver "modesetting"
EndSection
